api_platform:
  exception_to_status:
    App\Exception\ArticleNotFoundException: 404

  formats:
    json: ['application/json']

  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header

  title: 'Pentiminax API'
  version: '1.0.0'